version: 2
updates:
  - package-ecosystem: "composer" # You can also use "npm", "pip", etc.
    directory: "/" # Root directory of the project
    schedule:
      interval: "weekly" # Can be "daily", "weekly", or "monthly"
    commit-message:
      prefix: "deps"
